### ISSUE TITLE
contact link broken

### ISSUE THREAD

**Issue by NirmalSilwal** [gaushikmr/gaushikmr#4]
Hi @gaushikmr your social media contact links are broken in your readme profile.

Would love to connect with you in Linkedln.

**Comment by Gaushikmr** [comment]
@NirmalSilwal Sure :) Linkedin:https://www.linkedin.com/in/gaushik-m-r-08a58a135/

**Comment by NirmalSilwal** [comment]
Thanks

Have sent you connection in Linkedln.
